apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-tg-com-tls
spec:
  secretName: k8s-tg-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-tg.com
  dnsNames:
    - k8s-tg.com
    - www.k8s-tg.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s-tg.com
          - www.k8s-tg.com
